### ISSUE TITLE
Wanting to add more features.

### ISSUE THREAD

**Issue by AdityaSeth777** [Sabyasachi-Seal/LeetCode-to-Github#2]
Sabyasachi Da, I want to add the feature for automating solutions from Codechef or/and GFG.
I want to add an additional file thus enabling users to select which platform they want to choose. 

I want to contribute to it.
Can I ?

Aditya.
(You mentioned in your Hacktoberfest demo video that one should raise an issue before contributing, so :'))

**Comment by Sabyasachi-Seal** [comment]
Go ahead, @AdityaSeth777 , try to make it into a new file, if incase there are any fixes to the current script.

**Comment by AdityaSeth777** [comment]
Aye aye captain.

On it.

**Comment by Sabyasachi-Seal** [comment]
Any updates on this ? @AdityaSeth777

**Comment by AdityaSeth777** [comment]
Once my exams get over, I'll do it.

Automata is making my life worse.

**Comment by Sabyasachi-Seal** [comment]
@AdityaSeth777 Reminder
