### ISSUE TITLE
Bugs and improvements

### ISSUE THREAD

**Issue by AdityaSeth777** [Sabyasachi-Seal/LeetCode-to-Github#8]
### I found some bugs:

1. The processed problems doesn't cross over 65-70 whereas the user has done over 200 or more problems. Issues with pages.
2. The program keeps getting stuck on solved premium problems (that were once free or made free during contests/challenges).

### Improvements (Also can be termed as a bug):

1. Suppose someone has succesfully solved a problem and then attempts to solve it using a different method and fails, this program takes the failed attempt into error and not the successfully solved one.

**Comment by Sabyasachi-Seal** [comment]
@AdityaSeth777 Updates ? Progress ?

**Comment by AdityaSeth777** [comment]
On it. Currently on vacation :)

**Comment by Sabyasachi-Seal** [comment]
Guessing there is no progress on this ?
